import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Archive,
  BarChart3,
  Bell,
  BookOpen,
  FileSearch,
  GitBranch,
  History,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  Lock,
  Mail,
  Monitor,
  Plug,
  Puzzle,
  Rocket,
  ScrollText,
  Settings,
  Shield,
  ShieldAlert,
  Smile,
  Sparkles,
  Ticket,
  Wrench,
} from "lucide-react";

const categoryIconsByName: Readonly<Record<string, LucideIcon>> = {
  activity: Activity,
  archive: Archive,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  "file-search": FileSearch,
  "git-branch": GitBranch,
  history: History,
  "key-round": KeyRound,
  languages: Languages,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  lock: Lock,
  mail: Mail,
  monitor: Monitor,
  plug: Plug,
  puzzle: Puzzle,
  rocket: Rocket,
  "scroll-text": ScrollText,
  settings: Settings,
  shield: Shield,
  "shield-alert": ShieldAlert,
  smile: Smile,
  sparkles: Sparkles,
  ticket: Ticket,
  wrench: Wrench,
};

export function resolveCategoryIcon(iconName: string): LucideIcon {
  return categoryIconsByName[iconName] ?? Settings;
}
