export type TicketsErrorCode =
  | 'NOT_FOUND'
  | 'ORIGIN_UNIT_NOT_FOUND'
  | 'ORIGIN_UNIT_REQUIRED'
  | 'SERVICE_NOT_FOUND'
  | 'SERVICE_REQUIRED'
  | 'SERVICE_NOT_OFFERED'
  | 'FORM_VERSION_REQUIRED'
  | 'FORM_VERSION_NOT_FOUND'
  | 'FORM_VERSION_SERVICE_MISMATCH'
  | 'FORM_VERSION_NOT_ACTIVE'
  | 'INVALID_STATUS_TRANSITION'
  | 'STATUS_CHANGE_FORBIDDEN'
  | 'FORBIDDEN'
  | 'INVALID_TITLE'
  | 'INVALID_DESCRIPTION'
  | 'REQUESTER_NOT_FOUND'
  | 'ROUTING_UNAVAILABLE'
  | 'ASSIGNMENT_UNAVAILABLE'
  | 'GROUP_INBOX_DISABLED'
  | 'TICKET_NOT_CLAIMABLE'
  | 'PARTICIPANTS_DISABLED'
  | 'PARTICIPANT_NOT_FOUND'
  | 'PARTICIPANT_DUPLICATE'
  | 'INVALID_PARTICIPANT_ROLE'
  | 'PARTICIPANT_IDENTITY_REQUIRED'
  | 'PARTICIPANT_USER_NOT_FOUND'
  | 'PARTICIPANT_GROUP_NOT_FOUND'
  | 'PARTICIPANT_LOCKED'
  | 'CHAT_MESSAGE_TYPES_DISABLED'
  | 'INVALID_MESSAGE_TYPE'
  | 'INVALID_MESSAGE_BODY'
  | 'MESSAGE_TYPE_NOT_ALLOWED'
  | 'TIME_LOG_NOT_FOUND'
  | 'OVERLAPPING_TIMER'
  | 'TIME_LOG_NOT_ACTIVE'
  | 'TIME_LOG_IMMUTABLE'
  | 'ATTACHMENTS_DISABLED'
  | 'ATTACHMENT_NOT_FOUND'
  | 'ATTACHMENT_REQUIRED'
  | 'ATTACHMENT_TOO_LARGE'
  | 'ATTACHMENT_TYPE_NOT_ALLOWED'
  | 'ATTACHMENT_FILENAME_INVALID'
  | 'ATTACHMENT_LIMIT_REACHED'
  | 'CLASSIFICATION_DOWNGRADE'
  | 'ATTACHMENTS_STORAGE_UNAVAILABLE';

export class TicketsError extends Error {
  constructor(
    readonly code: TicketsErrorCode,
    message = code,
  ) {
    super(message);
    this.name = 'TicketsError';
  }
}
