export const ticketsTestIds = {
  ouIt: 'ou-it',
  ouHr: 'ou-hr',
  ouRoot: 'ou-root',
  serviceVpn: 'service-vpn',
  serviceDraft: 'service-draft',
  serviceAccess: 'service-access',
  formVpnV1: 'form-vpn-v1',
  formVpnV2: 'form-vpn-v2',
  formOther: 'form-other',
  formAccessV1: 'form-access-v1',
  groupIt: 'group-it',
  requester: 'user-requester',
  watcher: 'user-watcher',
  agentIt: 'user-agent-it',
  agentItPeer: 'user-agent-it-peer',
  agentHr: 'user-agent-hr',
  adminIt: 'user-admin-it',
  superAdmin: 'user-super-admin',
} as const;
