import {fetchEdgeBootstrap,type EdgeExtensionBootstrap} from './bootstrap-client';import {attachEdgeSocket,beginPolling,createEdgeSocketHandle,joinTicketRoom,runPollingOnce,tearDownEdgeSocket} from './edge-socket';import {resetEventDedup,ticketIdForEvent} from './event-dedup';import type {ExtensionStatus} from './extension-messages';import {acknowledgeRemoteRequest,fetchExtensionThread,fetchPendingRemoteTicketIds,sendExtensionReply} from './extension-ticket-api';import {fetchExtensionInbox} from './fetch-extension-inbox';import {clearAccessToken,readAccessToken,readApiBaseUrl,writeAccessToken,writeApiBaseUrl} from './memory-token';import {openDeskUrl} from './open-in-desk';import {clearPendingRemoteTicketIds,forgetPendingRemote,mergePendingRemoteTicketIds,readPendingRemoteTicketIds} from './pending-remote';import {sendNotificationReceipt} from './receipts-client';import {readNotificationState,resetNotificationState} from './notification-state';import {unreadAlarmName} from './polling-fallback';
const handle=createEdgeSocketHandle();let bootstrap:EdgeExtensionBootstrap|null=null;
export async function startEdgeSession(){tearDownEdgeSocket(handle);const token=await readAccessToken(),api=await readApiBaseUrl();if(!token||!api){bootstrap=null;return;}bootstrap=await fetchEdgeBootstrap({apiBaseUrl:api,accessToken:token}).catch(()=>null);if(!bootstrap||!bootstrap.allowed)return;await mergePendingRemoteTicketIds(await fetchPendingRemoteTicketIds({apiBaseUrl:api,accessToken:token}).catch(()=>[]));if(bootstrap.wsEnabled)attachEdgeSocket(handle,api,token,bootstrap);else if(bootstrap.pollingFallbackEnabled)await beginPolling(handle,api,token,bootstrap);}
export async function runEdgePollingAlarm(){const token=await readAccessToken(),api=await readApiBaseUrl();if(!token||!api)return;const b=bootstrap??await fetchEdgeBootstrap({apiBaseUrl:api,accessToken:token}).catch(()=>null);if(!b?.allowed)return;bootstrap=b;await runPollingOnce(api,token,b);}
export async function setEdgeSession(api:string,token:string){await writeApiBaseUrl(api);await writeAccessToken(token);await startEdgeSession();}
export async function clearEdgeSession(){tearDownEdgeSocket(handle);resetEventDedup();await clearPendingRemoteTicketIds();await resetNotificationState();bootstrap=null;await clearAccessToken();}
export async function readEdgeStatus():Promise<ExtensionStatus>{const token=await readAccessToken(),n=await readNotificationState();return{signedIn:!!token,allowed:bootstrap?.allowed===true,reason:bootstrap?.reason??'UNAUTHENTICATED',connected:handle.connected,polling:handle.socket===null&&bootstrap?.pollingFallbackEnabled===true,deskPublicUrl:bootstrap?.deskPublicUrl??'',subjectId:bootstrap?.subjectId??'',chatEnabled:bootstrap?.chatEnabled!==false,remoteEnabled:bootstrap?.remoteEnabled!==false,pendingRemoteTicketIds:await readPendingRemoteTicketIds(),notificationUnread:n.unread,actionRequired:n.actionRequired};}
export async function loadEdgeInbox(){const a=await requireSession();return fetchExtensionInbox(a);}
export async function loadEdgeThread(id:string){const a=await requireSession();joinTicketRoom(handle,id);return fetchExtensionThread({...a,ticketId:id,maxMessages:a.bootstrap.chatMaxMessagesPerTicket});}
export async function sendEdgeReply(id:string,body:string){const a=await requireSession();if(!a.bootstrap.chatEnabled)throw new Error('Chat is disabled');return sendExtensionReply({...a,ticketId:id,body});}
export async function ackEdgeRemote(id:string){const a=await requireSession();await acknowledgeRemoteRequest({...a,ticketId:id});await forgetPendingRemote(id);}
export async function onEdgeNotificationClicked(id:string){const token=await readAccessToken(),api=await readApiBaseUrl();if(!bootstrap||!token)return;const ticket=await ticketIdForEvent(id);openDeskUrl(bootstrap.deskPublicUrl,ticket);const n=await readNotificationState();if(n.unread>0){const nextAction=n.actionRequired>0?1:0;await chrome.storage.session.set({notificationState:{unread:n.unread-1,actionRequired:Math.max(0,n.actionRequired-nextAction)}});};if(bootstrap.receiptsEnabled)try{await sendNotificationReceipt({apiBaseUrl:api,accessToken:token,notificationId:id,eventId:id,kind:'opened'});}catch{}}
async function requireSession(){const token=await readAccessToken(),api=await readApiBaseUrl();if(!token||!bootstrap||!bootstrap.allowed)throw new Error('Not signed in');return{apiBaseUrl:api,accessToken:token,bootstrap,subjectId:bootstrap.subjectId};}
