/**
 * Paket 3.1: texts the bot writes into Teams (bs/en). Cards are rendered by
 * Teams, not by our frontend, so these strings live in the backend; the
 * product name always comes from branding (nothing is hard-coded).
 */
export type TeamsLocale = 'bs' | 'en';

const texts = {
  bs: {
    welcomeTitle: 'Dobro došli u {app}',
    welcomeLinked: 'Vaš Teams nalog je povezan s nalogom {name}. Ovdje ćete dobijati obavijesti i moći odgovarati na tikete.',
    notLinked: 'Vaš Teams nalog nije povezan s nalogom u aplikaciji – obratite se administratoru.',
    helpTitle: 'Šta mogu uraditi',
    helpNewTicket: '**novi tiket** – prijava novog tiketa',
    helpMyTickets: '**moji tiketi** – zadnjih 5 otvorenih tiketa',
    helpHelp: '**pomoć** – ova poruka',
    helpChannel: 'U kanalu: **@bot poveži** povezuje kanal s grupom, **@bot odspoji** uklanja vezu.',
    myTicketsTitle: 'Moji otvoreni tiketi',
    myTicketsEmpty: 'Nemate otvorenih tiketa.',
    open: 'Otvori',
    openApp: 'Otvori aplikaciju',
    newTicketSoon: 'Kreiranje tiketa iz Teamsa trenutno nije dostupno. Tiket možete prijaviti u aplikaciji.',
    newTicketDisabled: 'Kreiranje tiketa iz Teamsa je isključeno. Tiket možete prijaviti u aplikaciji.',
    linkTitle: 'Poveži kanal s grupom',
    linkChoose: 'Izaberite grupu čiji će se događaji objavljivati u ovom kanalu.',
    linkGroup: 'Grupa',
    linkSubmit: 'Poveži',
    linkNone: 'Nemate grupa koje možete povezati s kanalom.',
    linkForbidden: 'Nemate pravo povezivanja kanala.',
    linkOnlyChannel: 'Povezivanje radi samo u kanalu tima.',
    linkDone: 'Kanal je povezan s grupom **{group}**.',
    unlinkDone: 'Uklonjeno veza: {count}.',
    unlinkNone: 'Ovaj kanal nije povezan ni s jednom grupom kojom upravljate.',
    channelsDisabled: 'Obavijesti u kanale su isključene u postavkama.',
    actionUnavailable: 'Ova akcija još nije dostupna.',
    actionFailed: 'Akcija nije uspjela. Pokušajte ponovo ili otvorite aplikaciju.',
    reply: 'Odgovori',
    replyPlaceholder: 'Javni odgovor podnosiocu…',
    note: 'Interna bilješka',
    notePlaceholder: 'Vidljivo samo agentima…',
    send: 'Pošalji',
    claim: 'Preuzmi',
    approve: 'Odobri',
    reject: 'Odbij',
    rejectComment: 'Razlog odbijanja (obavezno)',
    fieldService: 'Servis',
    fieldPriority: 'Prioritet',
    fieldStatus: 'Status',
    fieldAssignee: 'Dodijeljeno',
    fieldDue: 'Rok',
    fieldRisk: 'Rizik',
    fieldWindow: 'Termin',
    unassigned: 'Nije preuzet',
    hiddenTitle: 'Naslov nije prikazan u kanalu',
    doneClaimed: '✓ Tiket je preuzet.',
    doneReplied: '✓ Odgovor je poslan.',
    doneNoted: '✓ Interna bilješka je dodana.',
    doneApproved: '✓ Odobreno.',
    doneRejected: '✓ Odbijeno.',
    doneVoted: '✓ Vaš glas je zabilježen.',
    doneTicketCreated: '✓ Tiket {number} je kreiran.',
    errStale: 'U međuvremenu je promijenjeno – kartica je osvježena.',
    errForbidden: 'Nemate pravo na ovu akciju.',
    errInvalid: 'Provjerite unesene podatke.',
    errTextLength: 'Tekst mora imati od 2 do 4000 znakova.',
    errReasonRequired: 'Razlog odbijanja je obavezan.',
    errNotFound: 'Stavka više ne postoji ili vam nije dostupna.',
    createTitle: 'Novi tiket',
    createService: 'Servis',
    createServicePlaceholder: 'Počnite kucati naziv servisa…',
    createTicketTitle: 'Naslov',
    createDescription: 'Opis',
    createImpact: 'Uticaj',
    createUrgency: 'Hitnost',
    createSubmit: 'Kreiraj tiket',
    createNeedsForm: 'Ovaj servis ima obavezan formular – tiket prijavite u aplikaciji.',
    createNoServices: 'Nema servisa za koje se tiket može prijaviti iz Teamsa.',
    createFromMessage: 'Iz Teams poruke',
    levelLOW: 'Nizak',
    levelMEDIUM: 'Srednji',
    levelHIGH: 'Visok',
    levelCRITICAL: 'Kritičan',
    helpTicket: '**tiket HD-123** (ili samo broj) – kartica tiketa',
    helpSearch: '**traži <tekst>** – pretraga baze znanja',
    helpApprovals: '**odobrenja** – odobrenja koja čekaju vas',
    helpStatus: '**status** – prekidi i planirani radovi',
    helpAgentTitle: 'Za agente',
    helpAssigned: '**dodijeljeni** – vaši tiketi po SLA roku',
    helpQueue: '**red** – nepreuzeti tiketi vaših grupa',
    helpSla: '**sla** – tiketi s ugroženim ili probijenim rokom',
    helpCab: '**cab** – promjene koje čekaju vaš glas',
    helpOnCall: '**dežurni** – ko je trenutno dežuran',
    openAll: 'Otvori sve u aplikaciji',
    shownOf: 'Prikazano {shown} od {total}.',
    ticketTitle: 'Tiket {number}',
    ticketNotFound: 'Tiket {ref} ne postoji ili vam nije dostupan.',
    ticketUsage: 'Napišite broj tiketa, npr. **tiket HD-123**.',
    fieldGroup: 'Grupa',
    fieldRequester: 'Podnosilac',
    slaBreached: 'SLA probijen',
    slaAtRisk: 'SLA ugrožen',
    searchTitle: 'Baza znanja: „{query}“',
    searchUsage: 'Napišite šta tražite, npr. **traži vpn**.',
    searchEmpty: 'Nema članaka za ovaj upit.',
    searchUnavailable: 'Baza znanja nije dostupna.',
    openArticle: 'Otvori članak',
    approvalsTitle: 'Odobrenja koja čekaju vas',
    approvalsEmpty: 'Nemate odobrenja na čekanju.',
    statusTitle: 'Status servisa',
    statusActive: 'Aktivni prekidi',
    statusPlanned: 'Planirani radovi',
    statusAllGood: 'Trenutno nema prijavljenih prekida.',
    statusNoPlanned: 'Nema planiranih radova.',
    statusUnavailable: 'Statusna stranica je isključena.',
    assignedTitle: 'Vaši dodijeljeni tiketi',
    assignedEmpty: 'Nemate dodijeljenih otvorenih tiketa.',
    queueTitle: 'Red – nepreuzeti tiketi',
    queueEmpty: 'Nema nepreuzetih tiketa u vašim grupama.',
    slaTitle: 'Tiketi s ugroženim ili probijenim SLA',
    slaEmpty: 'Nema tiketa s ugroženim ili probijenim rokom.',
    cabTitle: 'Promjene koje čekaju vaš glas',
    cabEmpty: 'Nema promjena koje čekaju vaš glas.',
    cabUnavailable: 'Upravljanje promjenama nije aktivno.',
    onCallTitle: 'Dežurni',
    onCallNobody: 'nema dežurnog',
    onCallUntil: 'do {time}',
    onCallMine: 'Vaše dežurstvo: {group} do {time}.',
    onCallNext: 'Vaše sljedeće dežurstvo: {group}, {from} – {to}.',
    onCallEmpty: 'Nema grupa s rasporedom dežurstva.',
    onCallUnavailable: 'Dežurstva nisu dostupna.',
    agentOnly: 'Ova komanda je dostupna samo agentima.',
    createNext: 'Dalje',
    interceptTitle: 'Prije nego što pošaljete',
    interceptBody: 'Ovi članci možda već rješavaju vaš problem:',
    interceptResolved: 'Riješeno, ne treba tiket',
    interceptCreate: 'Ipak kreiraj tiket',
    doneDeflected: '✓ Drago nam je da je riješeno. Tiket nije kreiran.',
  },
  en: {
    welcomeTitle: 'Welcome to {app}',
    welcomeLinked: 'Your Teams account is linked to {name}. You will get notifications here and can reply to tickets.',
    notLinked: 'Your Teams account is not linked to an account in the application – please contact your administrator.',
    helpTitle: 'What I can do',
    helpNewTicket: '**new ticket** – report a new ticket',
    helpMyTickets: '**my tickets** – your last 5 open tickets',
    helpHelp: '**help** – this message',
    helpChannel: 'In a channel: **@bot link** links the channel to a group, **@bot unlink** removes the link.',
    myTicketsTitle: 'My open tickets',
    myTicketsEmpty: 'You have no open tickets.',
    open: 'Open',
    openApp: 'Open application',
    newTicketSoon: 'Creating tickets from Teams is not available yet. You can report a ticket in the application.',
    newTicketDisabled: 'Creating tickets from Teams is turned off. You can report a ticket in the application.',
    linkTitle: 'Link channel to a group',
    linkChoose: 'Choose the group whose events will be posted to this channel.',
    linkGroup: 'Group',
    linkSubmit: 'Link',
    linkNone: 'You have no groups you can link to a channel.',
    linkForbidden: 'You are not allowed to link channels.',
    linkOnlyChannel: 'Linking works only in a team channel.',
    linkDone: 'The channel is linked to the group **{group}**.',
    unlinkDone: 'Links removed: {count}.',
    unlinkNone: 'This channel is not linked to any group you manage.',
    channelsDisabled: 'Channel notifications are turned off in the settings.',
    actionUnavailable: 'This action is not available yet.',
    actionFailed: 'The action failed. Try again or open the application.',
    reply: 'Reply',
    replyPlaceholder: 'Public reply to the requester…',
    note: 'Internal note',
    notePlaceholder: 'Visible to agents only…',
    send: 'Send',
    claim: 'Claim',
    approve: 'Approve',
    reject: 'Reject',
    rejectComment: 'Reason for rejection (required)',
    fieldService: 'Service',
    fieldPriority: 'Priority',
    fieldStatus: 'Status',
    fieldAssignee: 'Assigned to',
    fieldDue: 'Due',
    fieldRisk: 'Risk',
    fieldWindow: 'Window',
    unassigned: 'Not claimed',
    hiddenTitle: 'Title not shown in channels',
    doneClaimed: '✓ Ticket claimed.',
    doneReplied: '✓ Reply sent.',
    doneNoted: '✓ Internal note added.',
    doneApproved: '✓ Approved.',
    doneRejected: '✓ Rejected.',
    doneVoted: '✓ Your vote was recorded.',
    doneTicketCreated: '✓ Ticket {number} was created.',
    errStale: 'This changed in the meantime – the card was refreshed.',
    errForbidden: 'You are not allowed to do this.',
    errInvalid: 'Please check the entered data.',
    errTextLength: 'The text must have 2 to 4000 characters.',
    errReasonRequired: 'A reason for rejection is required.',
    errNotFound: 'The item no longer exists or is not available to you.',
    createTitle: 'New ticket',
    createService: 'Service',
    createServicePlaceholder: 'Start typing a service name…',
    createTicketTitle: 'Title',
    createDescription: 'Description',
    createImpact: 'Impact',
    createUrgency: 'Urgency',
    createSubmit: 'Create ticket',
    createNeedsForm: 'This service has a required form – please report the ticket in the application.',
    createNoServices: 'There are no services a ticket can be reported for from Teams.',
    createFromMessage: 'From a Teams message',
    levelLOW: 'Low',
    levelMEDIUM: 'Medium',
    levelHIGH: 'High',
    levelCRITICAL: 'Critical',
    helpTicket: '**ticket HD-123** (or just the number) – ticket card',
    helpSearch: '**search <text>** – knowledge base search',
    helpApprovals: '**approvals** – approvals waiting for you',
    helpStatus: '**status** – outages and planned maintenance',
    helpAgentTitle: 'For agents',
    helpAssigned: '**assigned** – your tickets by SLA deadline',
    helpQueue: '**queue** – unclaimed tickets of your groups',
    helpSla: '**sla** – tickets with an at-risk or breached deadline',
    helpCab: '**cab** – changes waiting for your vote',
    helpOnCall: '**on-call** – who is on call now',
    openAll: 'Open all in the application',
    shownOf: 'Showing {shown} of {total}.',
    ticketTitle: 'Ticket {number}',
    ticketNotFound: 'Ticket {ref} does not exist or is not available to you.',
    ticketUsage: 'Type a ticket number, e.g. **ticket HD-123**.',
    fieldGroup: 'Group',
    fieldRequester: 'Requester',
    slaBreached: 'SLA breached',
    slaAtRisk: 'SLA at risk',
    searchTitle: 'Knowledge base: “{query}”',
    searchUsage: 'Type what you are looking for, e.g. **search vpn**.',
    searchEmpty: 'No articles match this query.',
    searchUnavailable: 'The knowledge base is not available.',
    openArticle: 'Open article',
    approvalsTitle: 'Approvals waiting for you',
    approvalsEmpty: 'You have no pending approvals.',
    statusTitle: 'Service status',
    statusActive: 'Active outages',
    statusPlanned: 'Planned maintenance',
    statusAllGood: 'No outages are reported right now.',
    statusNoPlanned: 'No planned maintenance.',
    statusUnavailable: 'The status page is turned off.',
    assignedTitle: 'Your assigned tickets',
    assignedEmpty: 'You have no open assigned tickets.',
    queueTitle: 'Queue – unclaimed tickets',
    queueEmpty: 'There are no unclaimed tickets in your groups.',
    slaTitle: 'Tickets with an at-risk or breached SLA',
    slaEmpty: 'No tickets with an at-risk or breached deadline.',
    cabTitle: 'Changes waiting for your vote',
    cabEmpty: 'No changes are waiting for your vote.',
    cabUnavailable: 'Change management is not active.',
    onCallTitle: 'On call',
    onCallNobody: 'nobody on call',
    onCallUntil: 'until {time}',
    onCallMine: 'You are on call: {group} until {time}.',
    onCallNext: 'Your next shift: {group}, {from} – {to}.',
    onCallEmpty: 'No groups have an on-call schedule.',
    onCallUnavailable: 'On-call is not available.',
    agentOnly: 'This command is available to agents only.',
    createNext: 'Next',
    interceptTitle: 'Before you send',
    interceptBody: 'These articles may already solve your problem:',
    interceptResolved: 'Solved, no ticket needed',
    interceptCreate: 'Create the ticket anyway',
    doneDeflected: '✓ Glad it is solved. No ticket was created.',
  },
} as const;

export type TeamsTextKey = keyof (typeof texts)['bs'];

export function teamsText(locale: TeamsLocale, key: TeamsTextKey, params: Record<string, string | number> = {}): string {
  return texts[locale][key].replace(/\{(\w+)\}/g, (match, name: string) => (name in params ? String(params[name]) : match));
}

export function toTeamsLocale(value: string | null | undefined): TeamsLocale {
  return value?.toLowerCase().startsWith('en') ? 'en' : 'bs';
}

const statusLabels: Record<TeamsLocale, Record<string, string>> = {
  bs: { PENDING: 'Na čekanju', UNROUTED: 'Nerutiran', PENDING_APPROVAL: 'Čeka odobrenje', ASSIGNED: 'Dodijeljen', IN_PROGRESS: 'U radu', WAITING_FOR_USER: 'Čeka korisnika', RESOLVED: 'Riješen', CLOSED: 'Zatvoren', ARCHIVED: 'Arhiviran' },
  en: { PENDING: 'Pending', UNROUTED: 'Unrouted', PENDING_APPROVAL: 'Pending approval', ASSIGNED: 'Assigned', IN_PROGRESS: 'In progress', WAITING_FOR_USER: 'Waiting for user', RESOLVED: 'Resolved', CLOSED: 'Closed', ARCHIVED: 'Archived' },
};

export function teamsStatusLabel(locale: TeamsLocale, status: string): string {
  return statusLabels[locale][status] ?? status;
}

const priorityLabels: Record<TeamsLocale, Record<string, string>> = {
  bs: { LOW: 'Nizak', MEDIUM: 'Srednji', HIGH: 'Visok', CRITICAL: 'Kritičan' },
  en: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', CRITICAL: 'Critical' },
};

export function teamsPriorityLabel(locale: TeamsLocale, value: string): string {
  return priorityLabels[locale][value] ?? value;
}

/** Headline of a notification card, by notification type (fallback: generic). */
const headlines: Record<TeamsLocale, Record<string, string>> = {
  bs: {
    'ticket.created': 'Novi tiket u grupi',
    'ticket.assigned': 'Tiket vam je dodijeljen',
    'ticket.forwarded': 'Tiket je proslijeđen',
    'ticket.message': 'Nova poruka na tiketu',
    'ticket.mentioned': 'Spomenuti ste u bilješci',
    'ticket.resolved': 'Tiket je riješen',
    'ticket.closed': 'Tiket je zatvoren',
    'ticket.approval': 'Odobrenje tiketa',
    'ticket.sla': 'SLA upozorenje',
    'sla.breached': 'SLA rok je probijen',
    'problem.assigned': 'Problem vam je dodijeljen',
    'problem.groupAssigned': 'Problem je dodijeljen grupi',
    'problem.knownError': 'Poznata greška',
    'problem.resolved': 'Problem je riješen',
    'problem.targetDue': 'Rok problema se približava',
    'problem.recurrence': 'Problem se ponavlja',
    'change.approvalRequested': 'Traži se vaš glas (CAB)',
    'change.decided': 'Odluka o promjeni',
    'change.startingSoon': 'Promjena počinje uskoro',
    'change.overdue': 'Promjena je prekoračila termin',
    'change.failed': 'Promjena nije uspjela',
    'oncall.reminder': 'Podsjetnik za dežurstvo',
    'oncall.shiftStarted': 'Dežurstvo je počelo',
    'oncall.swap': 'Zahtjev za zamjenu dežurstva',
    generic: 'Obavijest',
  },
  en: {
    'ticket.created': 'New ticket in the group',
    'ticket.assigned': 'Ticket assigned to you',
    'ticket.forwarded': 'Ticket forwarded',
    'ticket.message': 'New message on a ticket',
    'ticket.mentioned': 'You were mentioned in a note',
    'ticket.resolved': 'Ticket resolved',
    'ticket.closed': 'Ticket closed',
    'ticket.approval': 'Ticket approval',
    'ticket.sla': 'SLA warning',
    'sla.breached': 'SLA deadline breached',
    'problem.assigned': 'Problem assigned to you',
    'problem.groupAssigned': 'Problem assigned to the group',
    'problem.knownError': 'Known error',
    'problem.resolved': 'Problem resolved',
    'problem.targetDue': 'Problem target date is near',
    'problem.recurrence': 'Problem recurrence',
    'change.approvalRequested': 'Your CAB vote is requested',
    'change.decided': 'Change decision',
    'change.startingSoon': 'Change starts soon',
    'change.overdue': 'Change overran its window',
    'change.failed': 'Change failed',
    'oncall.reminder': 'On-call reminder',
    'oncall.shiftStarted': 'On-call shift started',
    'oncall.swap': 'On-call swap request',
    generic: 'Notification',
  },
};

export function teamsHeadline(locale: TeamsLocale, key: string): string {
  return headlines[locale][key] ?? headlines[locale].generic;
}
