import {extensionMessageTypes,type ExtensionInboxTicket,type ExtensionStatus,type ExtensionThreadMessage} from './lib/extension-messages';import {readApiBaseUrl} from './lib/memory-token';import {openDeskUrl} from './lib/open-in-desk';import {openQuickAssistFromUserClick} from './lib/open-quick-assist';import {bindErrorElement,describeConnectionStatus,signInWithPassword} from './popup-session';import {renderThreadMessages} from './popup-thread';import {getLocale,initI18n,setLocale,t} from './lib/i18n';
const $=(id:string)=>document.getElementById(id);const statusEl=$('connection-status'),formEl=$('login-form'),workspace=$('workspace'),loginView=$('login-view'),inbox=$('inbox'),empty=$('inbox-empty'),thread=$('thread'),messages=$('messages'),replyForm=$('reply-form'),replyBody=$('reply-body'),qaPanel=$('quick-assist-panel'),qaButton=$('open-quick-assist'),errors=bindErrorElement($('error'));
let selected:string|null=null;let selectedTicket:ExtensionInboxTicket|null=null;let latest:ExtensionStatus|null=null;
function text(id:string,key:keyof ReturnType<typeof labels>){const e=$(id);if(e)e.textContent=labels()[key];}
function labels(){return {subtitle:t('subtitle'),loginEyebrow:t('loginEyebrow'),loginTitle:t('loginTitle'),loginDescription:t('loginDescription'),api:t('api'),email:t('email'),password:t('password'),login:t('login'),workspaceEyebrow:t('workspaceEyebrow'),workspaceTitle:t('workspaceTitle'),tickets:t('tickets'),empty:t('empty'),openDesk:t('openDesk'),signOut:t('signOut'),actionTitle:t('actionTitle'),actionDescription:t('actionDescription'),openAction:t('openAction'),replyPlaceholder:t('replyPlaceholder'),replyHint:t('replyHint'),send:t('send'),openTicket:t('openTicket'),quickAssist:t('quickAssist'),quickAssistDescription:t('quickAssistDescription'),startQuickAssist:t('startQuickAssist')}}
function applyI18n(){const l=labels();for(const [id,k] of Object.entries({subtitle:'subtitle',loginEyebrow:'loginEyebrow',loginTitle:'loginTitle',loginDescription:'loginDescription',apiLabel:'api',emailLabel:'email',passwordLabel:'password',loginButton:'login',workspaceEyebrow:'workspaceEyebrow',workspaceTitle:'workspaceTitle',ticketsTitle:'tickets',inboxEmpty:'empty',openDesk:'openDesk',signOut:'signOut',actionTitle:'actionTitle',actionDescription:'actionDescription',actionOpen:'openAction',replyHint:'replyHint',replyButton:'send',openDeskTicket:'openTicket',qaTitle:'quickAssist',qaDescription:'quickAssistDescription',openQuickAssist:'startQuickAssist'} as const)){const e=$(id);if(e)e.textContent=l[k]}if(replyBody instanceof HTMLTextAreaElement)replyBody.placeholder=l.replyPlaceholder;const s=$('language-select') as HTMLSelectElement|null;if(s)s.value='auto';}
async function refresh(){const s=await chrome.runtime.sendMessage({type:extensionMessageTypes.statusGet}) as ExtensionStatus;latest=s;applyI18n();if(statusEl)statusEl.textContent=describeConnectionStatus(s);if($('api-base-url') instanceof HTMLInputElement&&($('api-base-url') as HTMLInputElement).value==='')($('api-base-url') as HTMLInputElement).value=await readApiBaseUrl()||'http://localhost:10001';formEl?.toggleAttribute('hidden',s.signedIn);loginView?.toggleAttribute('hidden',s.signedIn);workspace?.toggleAttribute('hidden',!s.signedIn);const c=$('notification-count');if(c){c.textContent=String(s.notificationUnread);c.toggleAttribute('hidden',s.notificationUnread===0)}if(s.signedIn)await renderInbox();}
async function renderInbox(){const r=await chrome.runtime.sendMessage({type:extensionMessageTypes.inboxGet}) as {tickets?:ExtensionInboxTicket[];error?:string};if(r.error){errors.show(r.error);return}const tickets=r.tickets??[];if(empty){empty.hidden=tickets.length>0;empty.textContent=t('empty')}if(inbox instanceof HTMLElement){inbox.replaceChildren();for(const ticket of tickets){const li=document.createElement('li');li.className='ticket-item';const b=document.createElement('button');b.type='button';b.innerHTML=`<span class="ticket-number">${ticket.ticketNumber}</span><strong>${escapeHtml(ticket.title)}</strong><span class="ticket-status">${escapeHtml(ticket.status)}</span>`;b.addEventListener('click',()=>void openThread(ticket));li.append(b);inbox.append(li)}}const count=$('ticket-count');if(count)count.textContent=String(tickets.length);}
async function openThread(ticket:ExtensionInboxTicket){selected=ticket.id;selectedTicket=ticket;if(thread)thread.hidden=false;const n=$('thread-number');if(n)n.textContent=ticket.ticketNumber;const title=$('thread-title');if(title)title.textContent=ticket.title;const s=latest;const pending=!!s?.pendingRemoteTicketIds.includes(ticket.id);if(qaPanel)qaPanel.hidden=!pending||s?.remoteEnabled===false;replyForm?.toggleAttribute('hidden',s?.chatEnabled===false);const r=await chrome.runtime.sendMessage({type:extensionMessageTypes.threadGet,ticketId:ticket.id}) as {messages?:ExtensionThreadMessage[];error?:string};if(r.error){errors.show(r.error);return}renderThreadMessages(messages,r.messages??[]);}
formEl?.addEventListener('submit',e=>{e.preventDefault();void submitLogin()});replyForm?.addEventListener('submit',e=>{e.preventDefault();void sendReply()});$('back-to-inbox')?.addEventListener('click',()=>{if(thread)thread.hidden=true});$('open-desk')?.addEventListener('click',()=>openDeskUrl(latest?.deskPublicUrl??''));$('open-desk-ticket')?.addEventListener('click',()=>openDeskUrl(latest?.deskPublicUrl??'',selected));$('sign-out')?.addEventListener('click',async()=>{await chrome.runtime.sendMessage({type:extensionMessageTypes.sessionClear});selected=null;await refresh()});
qaButton?.addEventListener('click',async()=>{if(!selected)return;openQuickAssistFromUserClick();try{await chrome.runtime.sendMessage({type:extensionMessageTypes.remoteAck,ticketId:selected})}catch{}if(qaPanel)qaPanel.hidden=true;alert(t('remoteOpened'));await refresh()});
$('language-select')?.addEventListener('change',async e=>{const v=(e.target as HTMLSelectElement).value as 'auto'|'bs'|'en';await setLocale(v);await refresh()});
$('open-notifications')?.addEventListener('click',()=>{const first=selectedTicket;if(first)void openThread(first);else void renderInbox()});
async function submitLogin(){const api=$('api-base-url'),email=$('email'),password=$('password');if(!(api instanceof HTMLInputElement)||!(email instanceof HTMLInputElement)||!(password instanceof HTMLInputElement))return;errors.hide();try{await signInWithPassword({apiBaseUrl:api.value.replace(/\/$/,''),email:email.value,password:password.value});password.value='';await refresh()}catch(e){errors.show(e instanceof Error?e.message:t('loginFailed'))}}
async function sendReply(){if(!selected||!(replyBody instanceof HTMLTextAreaElement))return;const body=replyBody.value.trim();if(!body)return;errors.hide();const r=await chrome.runtime.sendMessage({type:extensionMessageTypes.replySend,ticketId:selected,body}) as {error?:string};if(r.error){errors.show(r.error);return}replyBody.value='';const x=await chrome.runtime.sendMessage({type:extensionMessageTypes.threadGet,ticketId:selected}) as {messages?:ExtensionThreadMessage[]};renderThreadMessages(messages,x.messages??[]);}
function escapeHtml(v:string){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
async function init(){await initI18n();applyI18n();await refresh()}void init();